@startuml
package components <<Frame>> {
  map "**Logo**" as Logo {
    ""nw,ne,sw,se""//:string// => Color of shape
    ""blur""//:number// => Blur distance in pixels
    ""w,h""//:string// => Logo dimension in css unit
    ""border""//:boolean// => Border mode, no fill
    ""loading""//:boolean// => Loading animation mode
    ""dark""//:boolean|null// => B&W mode
    ""show""//:"both","left","right"// => Part of the logo to show
  }
  map "**Block**" as Block {
    ""img""//:string// => Background image
    ""cols,xl,lg,md,sm,xs""//:string// => Colums of block based on width
    ""parallax""//:number// => Parallax effect (default 0.5)
    ""notag""//:boolean// => No top tag
    ""dark""//:boolean// => Dark mode
  }
  map "**GDSC**" as GDSC {
    ""title""//:string// => Webpage title
    ""transparent""//:boolean// => Head is transparent
  }
  map "**Paragraph**" as Paragraph {
    ""no""//:number// => Paragraph number (auto)
    ""head""//:string// => Head of Paragraph
    ""body""//:string// => Body of Paragraph
    ""landing""//:boolean// => Landing page mode
  }
  map "**Bubble**" as Bubble {
    ""left,top""//:string// => CSS Position
    ""x,y""//:number// => Offset in ""vw""
    ""z""//:number// => Circle radius
    ""crop""//:boolean// => Crop outside parent
    ""fill""//:string// => Fill color or image
    ""damp""//:number// => Damping factor (0 to 1)
    "lag""//:number// => Scroll lagging factor (0 to 1)
    ""inline""//:boolean// => Inline not absolute
    ""speed""//:number// => Animation speed
    ""back""//:boolean// => Display has background
  }
  map "**Bubbles**" as Bubbles {
    ""amount""//:number// => Number of bubbles
    ""span""//:number// => Dispersion of bubbles (vw)
    ""img""//:strings// => Images split by ","
  }
  map "**Slider**" as Slider {
  }
  map "**Slide**" as Slide {
    ""img""//:string// => Cover image
    ""head""//:string// => Title
    ""date""//:string// => Date
  }
  Logo --> GDSC : Uses
  GDSC --> Paragraph : ""inject(paragraph)""
  Bubble --> Bubbles : Uses
  GDSC --> Bubble : ""inject(mouse)""
  GDSC --> Block : ""inject(mouse,pagedim)""
  Slide --> Slider : Uses
}
@enduml